name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build
      uses: rrbutani/tlt-github-action@0.4.2
      with:
        target: build
    # Disable format checking for now:
    # - name: Check
    #   uses: rrbutani/tlt-github-action@0.4.2
    #   with:
    #     target: check
